name: 'Comment Pull Request'
branding:
  icon: 'message-circle'
  color: 'blue'
description: 'Comments a pull request with the provided message'
inputs:
  message:
    description: 'Message that should be printed in the pull request'
    required: true
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    required: true
  reactions:
    description: 'You can set some reactions on your comments through the `reactions` input.'
  pr_number:
    description: 'Manual pull request number'
  comment_includes:
    description: 'The text that should be used to find comment in case of replacement.'
runs:
  using: 'node16'
  main: 'lib/index.js'
